### ISSUE TITLE
Hands not loaded in xrState

### ISSUE THREAD

**Issue by avaer** [webaverse/xrpackage#116]
We recently added hands tracking to the repos, however it doesn't seem to be picked up by some packages:

```
TypeError: Cannot read property '0' of undefined
    at new XRInputSource (http://localhost:59493/xrpackage/XR.js:620:50)
    at new XRSession (http://localhost:59493/xrpackage/XR.js:181:7)
    at EventTarget.iframeInit (http://localhost:59493/webxr-template.html:66:21)
    at async EventTarget.webxr-site@0.0.1 (http://localhost:59493/xrpackage.js:405:5)
    at async EventTarget.ensureRunStop (http://localhost:59493/xrpackage.js:2172:9)
    at async EventTarget.add (http://localhost:59493/xrpackage.js:527:5)
```

This was reported by @shu8 -- do you have a reproduction package for this error?

**Comment by avaer** [comment]
There is still no way to reproduce this on my end. I successfully load packages on https://xrpackage.org/edit.html and `master`.

This error looks like it's coming from xrState not having hands, which is a new addition:

https://github.com/webaverse/xrpackage/blob/master/xrpackage.js#L248

But it is in `master`. Is this caching?

**Comment by avaer** [comment]
If this cannot be reproduced anymore, can we close it?

**Comment by shu8** [comment]
I just rebased with `master` and it's not throwing this error anymore, I must have missed the recent commits.

Sorry for the confusion! I think this can be closed.
